const pizza = [
  {
    id: 1,
    number: 1,
    name: 'MARGHERITA',
    category: 'vegetariánska',
    weight: 420,
    price: 3.8,
    ingredients: ['paradajky', 'Eidam'],
    tags: ['syr'],
  },
  {
    id: 2,
    number: 5,
    name: 'QUATTRO FORMAGGI',
    category: 'vegetariánska',
    weight: 420,
    price: 4.8,
    ingredients: ['Eidam', 'Inovec', 'Hermelín', 'Niva'],
    tags: ['syr'],
  },
  {
    id: 3,
    number: 27,
    name: 'VEGETARIANA',
    category: 'vegetariánska',
    weight: 530,
    price: 4.8,
    ingredients: [
      'paradajky',
      'Eidam',
      'šampiňóny',
      'artičoky',
      'paprika',
      'špargľa',
      'ananás',
    ],
    tags: ['huby', 'hubová', 'hnusná', 'syr'],
  },
  {
    id: 4,
    number: 28,
    name: 'VEGETARIA',
    category: 'vegetariánska',
    weight: 490,
    price: 4.4,
    ingredients: ['paradajky', 'Eidam', 'kukurica', 'brokolica'],
    tags: ['syr'],
  },
  {
    id: 5,
    number: 220,
    name: 'VERDURA',
    category: 'vegetariánska',
    weight: 560,
    price: 4.8,
    ingredients: [
      'paradajky',
      'Eidam',
      'šampiňóny',
      'kukurica',
      'brokolica',
      'vajce',
      'artičoky',
    ],
    tags: ['huby', 'hubová', 'hnusná', 'syr'],
  },
  {
    id: 6,
    number: 223,
    name: 'HERMELIA',
    category: 'vegetariánska',
    weight: 510,
    price: 4.8,
    ingredients: [
      'paradajky',
      'Eidam',
      'kukurica',
      'oregáno',
      'Hermelín',
      'hrach',
    ],
    tags: ['syr'],
  },
  {
    id: 7,
    number: 233,
    name: 'AMERICANA',
    category: 'vegetariánska',
    weight: 540,
    price: 4.7,
    ingredients: ['paradajky', 'Eidam', 'hranolky'],
    tags: ['syr'],
  },
  {
    id: 8,
    number: 2,
    name: 'SICILIANA',
    category: 'rybacia',
    weight: 480,
    price: 4.7,
    ingredients: [
      'paradajky',
      'Eidam',
      'oregáno',
      'olivy',
      'sardelky',
      'kapary',
    ],
    tags: ['ryby', 'rybacia', 'syr'],
  },
  {
    id: 9,
    number: 3,
    name: 'FRUTTI DI MARE',
    category: 'rybacia',
    weight: 450,
    price: 5.3,
    ingredients: ['paradajky', 'cesnak', 'morské plody'],
    tags: ['ryby', 'rybacia'],
  },
  {
    id: 10,
    number: 15,
    name: 'AL TONNO',
    category: 'rybacia',
    weight: 510,
    price: 4.7,
    ingredients: ['paradajky', 'Eidam', 'cesnak', 'cibuľa', 'tuniak'],
    tags: ['ryby', 'rybacia', 'syr'],
  },
  {
    id: 11,
    number: 229,
    name: 'ADRIATICA',
    category: 'rybacia',
    weight: 510,
    price: 6,
    ingredients: [
      'Eidam',
      'šunka',
      'Mozzarella',
      'cibuľa',
      'tuniak',
      'smotana',
    ],
    tags: ['ryby', 'rybacia', 'syr'],
  },
  {
    id: 12,
    number: 231,
    name: 'CONTESA',
    category: 'rybacia',
    weight: 650,
    price: 6.1,
    ingredients: [
      'paradajky',
      'Eidam',
      'šunka',
      'slanina',
      'šampiňóny',
      'kukurica',
      'oregáno',
      'feferónky',
      'cibuľa',
      'tuniak',
      'paprika',
    ],
    tags: ['huby', 'hubová', 'ryby', 'rybacia', 'syr'],
  },
  {
    id: 13,
    number: 550,
    name: 'SARDELLE',
    category: 'rybacia',
    weight: 530,
    price: 5.1,
    ingredients: [
      'paradajky',
      'Eidam',
      'olivy',
      'sardelky',
      'sardinky',
      'kapary',
    ],
    tags: ['ryby', 'rybacia', 'syr'],
  },
  {
    id: 14,
    number: 552,
    name: 'MARINARA',
    category: 'rybacia',
    weight: 480,
    price: 6.9,
    ingredients: [
      'cesnak',
      'krevety',
      'mušle',
      'kalamáre',
      'bylinky',
    ],
    tags: ['ryby', 'rybacia'],
  },
  {
    id: 15,
    number: 8,
    name: 'DIAVOLA',
    category: 'pikantná',
    weight: 490,
    price: 4.8,
    ingredients: ['paradajky', 'Eidam', 'saláma', 'feferónky'],
    tags: ['syr'],
  },
  {
    id: 16,
    number: 12,
    name: 'VESUVIO',
    category: 'pikantná',
    weight: 640,
    price: 5.4,
    ingredients: [
      'paradajky',
      'Eidam',
      'šampiňóny',
      'vajce',
      'Niva',
      'feferónky',
      'olivy',
      'cibuľa',
    ],
    tags: ['huby', 'hubová', 'syr'],
  },
  {
    id: 17,
    number: 21,
    name: 'TRADIZIONALE',
    category: 'pikantná',
    weight: 570,
    price: 5.4,
    ingredients: [
      'paradajky',
      'Eidam',
      'slanina',
      'feferónky',
      'cibuľa',
      'klobása',
    ],
    tags: ['syr'],
  },
  {
    id: 18,
    number: 25,
    name: 'VIVALDI',
    category: 'pikantná',
    weight: 560,
    price: 5.2,
    ingredients: [
      'paradajky',
      'Eidam',
      'saláma',
      'feferónky',
      'olivy',
      'paprika',
      'kapary',
      'sardelky',
    ],
    tags: ['ryby', 'rybacia', 'syr'],
  },
  {
    id: 19,
    number: 29,
    name: 'LUCIFERO',
    category: 'pikantná',
    weight: 550,
    price: 5,
    ingredients: [
      'paradajky',
      'Eidam',
      'saláma',
      'feferónky',
      'olivy',
      'paprika',
    ],
    tags: ['syr'],
  },
  {
    id: 20,
    number: 30,
    name: 'CICLOPE',
    category: 'pikantná',
    weight: 560,
    price: 5.1,
    ingredients: [
      'paradajky',
      'Eidam',
      'saláma',
      'šampiňóny',
      'feferónky',
      'cibuľa',
    ],
    tags: ['huby', 'hubová', 'syr'],
  },
  {
    id: 21,
    number: 211,
    name: 'MEXICANA',
    category: 'pikantná',
    weight: 560,
    price: 5.2,
    ingredients: [
      'paradajky',
      'Eidam',
      'cibuľa',
      'paprika',
      'feferónky',
      'fazuľa',
    ],
    tags: ['syr'],
  },
  {
    id: 22,
    number: 224,
    name: 'LUX',
    category: 'pikantná',
    weight: 590,
    price: 5.2,
    ingredients: [
      'paradajky',
      'Eidam',
      'šunka',
      'slanina',
      'oregáno',
      'feferónky',
      'cesnak',
      'olivy',
      'cibuľa',
    ],
    tags: ['syr'],
  },
  {
    id: 23,
    number: 226,
    name: 'SOMBRERO',
    category: 'pikantná',
    weight: 560,
    price: 5.1,
    ingredients: [
      'paradajky',
      'Eidam',
      'slanina',
      'kukurica',
      'feferónky',
      'cesnak',
      'olivy',
      'fazuľa',
    ],
    tags: ['syr'],
  },
  {
    id: 24,
    number: 553,
    name: 'BAČOVSKÁ',
    category: 'pikantná',
    weight: 550,
    price: 6,
    ingredients: ['smotana', 'slanina', 'cibuľa', 'bryndza', 'kôpor'],
    tags: [],
  },
  {
    id: 25,
    number: 554,
    name: 'GAZDOVSKÁ',
    category: 'pikantná',
    weight: 570,
    price: 5.4,
    ingredients: ['paradajky', 'Eidam', 'klobása', 'údený syr'],
    tags: ['syr'],
  },
  {
    id: 26,
    number: 4,
    name: 'PROSCIUTTO',
    category: 'dámska',
    weight: 470,
    price: 4.4,
    ingredients: ['paradajky', 'Eidam', 'šunka'],
    tags: ['syr'],
  },
  {
    id: 27,
    number: 16,
    name: 'HAWAI',
    category: 'dámska',
    weight: 490,
    price: 4.7,
    ingredients: ['paradajky', 'Eidam', 'šunka', 'ananás'],
    tags: ['syr'],
  },
  {
    id: 28,
    number: 26,
    name: 'TI AMO',
    category: 'dámska',
    weight: 510,
    price: 4.8,
    ingredients: [
      'paradajky',
      'Eidam',
      'kukurica',
      'kuracie mäso',
      'špargľa',
    ],
    tags: ['hnusná', 'syr'],
  },
  {
    id: 29,
    number: 210,
    name: 'FRUTTA',
    category: 'dámska',
    weight: 400,
    price: 4.8,
    ingredients: [
      'škorica',
      'ovocie',
      'hrozienka',
      'orechy',
      'čokoláda',
      'vanilka',
    ],
    tags: ['Alica', 'Alicka'],
  },
  {
    id: 30,
    number: 212,
    name: 'SINGAPORE',
    category: 'dámska',
    weight: 480,
    price: 5.1,
    ingredients: [
      'paradajky',
      'Eidam',
      'Mozzarella',
      'ananás',
      'orechy',
    ],
    tags: ['syr'],
  },
  {
    id: 31,
    number: 6,
    name: 'CALZONE',
    category: 'ostatné',
    weight: 430,
    price: 4.8,
    ingredients: [
      'paradajky',
      'Eidam',
      'šunka',
      'šampiňóny',
      'artičoky',
    ],
    tags: ['huby', 'hubová', 'hnusná', 'syr'],
  },
  {
    id: 32,
    number: 9,
    name: 'QUATTRO STAGIONI',
    category: 'ostatné',
    weight: 530,
    price: 5.3,
    ingredients: [
      'paradajky',
      'Eidam',
      'šunka',
      'šampiňóny',
      'olivy',
      'artičoky',
      'kapary',
    ],
    tags: ['huby', 'hubová', 'hnusná', 'syr'],
  },
  {
    id: 33,
    number: 10,
    name: 'RENÉ',
    category: 'ostatné',
    weight: 610,
    price: 5.6,
    ingredients: [
      'paradajky',
      'Eidam',
      'šunka',
      'saláma',
      'šampiňóny',
      'vajce',
      'artičoky',
      'paprika',
    ],
    tags: ['huby', 'hubová', 'hnusná', 'syr'],
  },
  {
    id: 34,
    number: 13,
    name: 'PROSCIUTTO FUNGI',
    category: 'ostatné',
    weight: 520,
    price: 5.1,
    ingredients: ['paradajky', 'Eidam', 'šunka', 'šampiňóny'],
    tags: ['huby', 'hubová', 'syr'],
  },
  {
    id: 35,
    number: 14,
    name: 'CALABRIA',
    category: 'ostatné',
    weight: 540,
    price: 4.9,
    ingredients: [
      'paradajky',
      'Eidam',
      'slanina',
      'oregáno',
      'cibuľa',
      'paprika',
      'kapary',
    ],
    tags: ['syr'],
  },
  {
    id: 36,
    number: 17,
    name: 'PIZZA SENDVIČ UFO',
    category: 'ostatné',
    weight: 680,
    price: 5.4,
    ingredients: [
      'paradajky',
      'Eidam',
      'šunka',
      'šampiňóny',
      'vajce',
    ],
    tags: ['huby', 'hubová', 'syr'],
  },
  {
    id: 37,
    number: 19,
    name: 'CAPRI',
    category: 'ostatné',
    weight: 480,
    price: 4.6,
    ingredients: [
      'paradajky',
      'Eidam',
      'kuracie mäso',
      'cesnak',
      'bazalka',
    ],
    tags: ['hnusná', 'syr'],
  },
  {
    id: 38,
    number: 20,
    name: 'COLOSEUM',
    category: 'ostatné',
    weight: 480,
    price: 5.2,
    ingredients: [
      'paradajky',
      'Eidam',
      'šunka',
      'Niva',
      'oregáno',
      'cesnak',
    ],
    tags: ['syr'],
  },
  {
    id: 39,
    number: 23,
    name: 'CAPRICCIOSA',
    category: 'ostatné',
    weight: 460,
    price: 4.9,
    ingredients: ['Eidam', 'šunka', 'šampiňóny', 'artičoky'],
    tags: ['huby', 'hubová', 'hnusná', 'syr'],
  },
  {
    id: 40,
    number: 24,
    name: 'RIALTO',
    category: 'ostatné',
    weight: 450,
    price: 4.9,
    ingredients: ['Eidam', 'saláma', 'šampiňóny', 'Niva'],
    tags: ['huby', 'hubová', 'syr'],
  },
  {
    id: 41,
    number: 31,
    name: 'MARCELLA',
    category: 'ostatné',
    weight: 560,
    price: 5.4,
    ingredients: [
      'paradajky',
      'Eidam',
      'šunka',
      'šampiňóny',
      'vajce',
      'Niva',
    ],
    tags: ['huby', 'hubová', 'syr'],
  },
  {
    id: 42,
    number: 32,
    name: 'CAROLINA',
    category: 'ostatné',
    weight: 560,
    price: 5.5,
    ingredients: [
      'paradajky',
      'Eidam',
      'šampiňóny',
      'kukurica',
      'kuracie mäso',
      'vajce',
      'Niva',
    ],
    tags: ['huby', 'hubová', 'hnusná', 'syr'],
  },
  {
    id: 43,
    number: 221,
    name: 'CRUDO',
    category: 'ostatné',
    weight: 620,
    price: 5.7,
    ingredients: [
      'paradajky',
      'Eidam',
      'šunka',
      'kukurica',
      'vajce',
      'paprika',
      'údené mäso',
      'hrach',
    ],
    tags: ['syr'],
  },
  {
    id: 44,
    number: 222,
    name: 'BOLOGNESE',
    category: 'ostatné',
    weight: 520,
    price: 5,
    ingredients: ['paradajky', 'Eidam', 'mäsová zmes', 'tymián'],
    tags: ['syr'],
  },
  {
    id: 45,
    number: 225,
    name: 'FATRA',
    category: 'ostatné',
    weight: 550,
    price: 6.2,
    ingredients: [
      'paradajky',
      'Eidam',
      'Mozzarella',
      'údené mäso',
      'chren',
    ],
    tags: ['syr'],
  },
  {
    id: 46,
    number: 227,
    name: 'GARGANO',
    category: 'ostatné',
    weight: 530,
    price: 5.3,
    ingredients: [
      'paradajky',
      'Eidam',
      'slanina',
      'šampiňóny',
      'klobása',
    ],
    tags: ['huby', 'hubová', 'syr'],
  },
  {
    id: 47,
    number: 228,
    name: 'SAN LORENZO',
    category: 'ostatné',
    weight: 500,
    price: 4.7,
    ingredients: [
      'paradajky',
      'Eidam',
      'kukurica',
      'kuracie mäso',
      'oregáno',
      'chren',
    ],
    tags: ['hnusná', 'syr'],
  },
  {
    id: 48,
    number: 230,
    name: 'PULS',
    category: 'ostatné',
    weight: 610,
    price: 6.1,
    ingredients: [
      'paradajky',
      'Eidam',
      'šunka',
      'slanina',
      'kukurica',
      'Niva',
      'oregáno',
      'Hermelín',
    ],
    tags: ['syr'],
  },
  {
    id: 49,
    number: 232,
    name: 'ROLLO',
    category: 'ostatné',
    weight: 530,
    price: 6.1,
    ingredients: [
      'paradajky',
      'Eidam',
      'šampiňóny',
      'Niva',
      'Hermelín',
      'údené mäso',
    ],
    tags: ['huby', 'hubová', 'syr'],
  },
  {
    id: 50,
    number: 234,
    name: 'PIZZA FAMILY',
    category: 'ostatné',
    weight: 890,
    price: 8.9,
    ingredients: ['paradajky', 'Eidam', 'Mozzarella', 'Inovec'],
    tags: ['syr'],
  },
  {
    id: 51,
    number: 237,
    name: 'NICOL',
    category: 'ostatné',
    weight: 530,
    price: 5.8,
    ingredients: [
      'paradajky',
      'Eidam',
      'slanina',
      'kukurica',
      'Hermelín',
      'údené mäso',
    ],
    tags: ['syr'],
  },
  {
    id: 52,
    number: 238,
    name: 'TOBY',
    category: 'ostatné',
    weight: 530,
    price: 5.2,
    ingredients: [
      'paradajky',
      'Eidam',
      'saláma',
      'kukurica',
      'cesnak',
      'kápia',
    ],
    tags: ['syr'],
  },
  {
    id: 53,
    number: 239,
    name: 'DENNY',
    category: 'ostatné',
    weight: 580,
    price: 5.3,
    ingredients: [
      'paradajky',
      'Eidam',
      'šunka',
      'šampiňóny',
      'kukurica',
      'Niva',
      'kápia',
    ],
    tags: ['huby', 'hubová', 'syr'],
  },
  {
    id: 54,
    number: 247,
    name: 'AMORE',
    category: 'ostatné',
    weight: 520,
    price: 6.1,
    ingredients: ['paradajky', 'Mozzarella', 'Gorgonzola', 'bazalka'],
    tags: ['syr'],
  },
  {
    id: 55,
    number: 248,
    name: 'FANTASIA',
    category: 'ostatné',
    weight: 670,
    price: 6.8,
    ingredients: [
      'paradajky',
      'Eidam',
      'Mozzarella',
      'losos',
      'špenát',
    ],
    tags: ['ryby', 'rybacia', 'syr'],
  },
  {
    id: 56,
    number: 249,
    name: 'ROMANA',
    category: 'ostatné',
    weight: 620,
    price: 9.2,
    ingredients: [
      'paradajky',
      'Mozzarella',
      'Gorgonzola',
      'šunka',
      'Prosciutto',
    ],
    tags: ['syr', 'šunka'],
  },
  {
    id: 57,
    number: 264,
    name: 'FUNGI',
    category: 'ostatné',
    weight: 620,
    price: 7.3,
    ingredients: ['paradajky', 'Eidam', 'Mozzarella', 'hríby'],
    tags: ['huby', 'hubová', 'syr'],
  },
  {
    id: 58,
    number: 270,
    name: 'QUATRO CARNE',
    category: 'ostatné',
    weight: 610,
    price: 6.1,
    ingredients: [
      'paradajky',
      'Eidam',
      'šunka',
      'slanina',
      'údené mäso',
      'klobása',
    ],
    tags: ['syr'],
  },
  {
    id: 59,
    number: 271,
    name: 'BAMBINO',
    category: 'ostatné',
    weight: 550,
    price: 5.4,
    ingredients: ['smotana', 'Eidam', 'Bambino', 'šunka', 'špenát'],
    tags: ['syr'],
  },
  {
    id: 60,
    number: 272,
    name: 'MARGHERITA ITALIANA',
    category: 'ostatné',
    weight: 520,
    price: 5.1,
    ingredients: ['paradajky', 'Mozzarella', 'bazalka'],
    tags: ['syr'],
  },
  {
    id: 61,
    number: 273,
    name: 'LUCIANO',
    category: 'ostatné',
    weight: 570,
    price: 5.6,
    ingredients: [
      'paradajky',
      'Eidam',
      'cesnak',
      'smotana',
      'krevety',
      'krabie mäso',
      'špenát',
    ],
    tags: ['ryby', 'rybacia', 'syr'],
  },
  {
    id: 62,
    number: 274,
    name: 'PRIMAVERA',
    category: 'vegetariánska',
    weight: 690,
    price: 5.1,
    ingredients: ['paradajky', 'Eidam', 'Cottage', 'zelenina'],
    tags: ['syr'],
  },
  {
    id: 63,
    number: 551,
    name: 'PROSCIUTO CRUDO',
    category: 'ostatné',
    weight: 520,
    price: 6.9,
    ingredients: ['paradajky', 'Eidam', 'šunka', 'Prosciutto'],
    tags: ['syr', 'šunka'],
  },
];

export default pizza;
